env:
  global:
    - HOST_UID=$UID
    - HOST_GID=$GID

services:
  - docker

script:
  - docker login --username=${DOCKER_USERNAME} --password=${DOCKER_PASSWORD}
  - echo "WP_SMTP_PASSWORD=test" > environment/default/wordpress.secret.env
  - make

after_failure:
  - ./docker-compose -f env/ci/docker-compose.yml logs

deploy:
  - provider: script
    skip_cleanup: true
    script: make docker-images-persistent
    on:
      branch: master

cache:
  directories:
    - ~/.composer/cache
    - ~/.cache
    - ~/.config/configstore
    - ~/.local
