env:
  global:
    - HOST_UID=$UID
    - HOST_GID=$GID

services:
  - docker

script:
  - make

after_failure:
  - ./docker-compose -f env/ci/docker-compose.yml logs

cache:
  directories:
    - ~/.composer/cache
