version: "2"

services:
  wordpress-build:
    image: allihoppa/allihoppa.nl:build
    container_name: allihoppa-nl-wordpress-build
    build:
      context: ./docker/build
    volumes:
      - ./public:/var/www
      - ~/.composer/:/home/.composer
    environment:
      HOME: /home/$LOCAL_USER_ID
      LOCAL_USER_ID: $LOCAL_USER_ID
      SYMFONY_ENV: "dev"
      # Add the GITHUB_TOKEN which is needed to setup Composer authentication configuration.
      # This value is taken from a variable, or as the docs say:
      # "Environment variables with only a key are resolved to their values on the machine Compose is running on,
      # which can be helpful for secret or host-specific values."
      # See: # https://docs.docker.com/compose/compose-file/#/environment
      GITHUB_TOKEN: $GITHUB_TOKEN

  wordpress:
    image: allihoppa/allihoppa.nl:base
    build:
      context: ./docker/base
    tty: true
    ports:
      - 80:80
    volumes:
      - ./public:/var/www
    env_file:
      - environment/dev/db.env
      - environment/dev/wordpress.env

  mysql:
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    env_file:
      - environment/dev/db.env
