version: "2"

networks:
  traefik:
    external:
      name: traefik_webgateway

services:
  js-build:
    container_name: allihoppa-nl-js-build
    image: allihoppa/allihoppa.nl:js-build
    build:
      context: ./docker/js-build
    user: $HOST_UID:$HOST_GID
    environment:
      HOME: /home
    volumes:
      # Bower config
      - ~/.config/configstore/bower:/home/.config/configstore/bower
      - ~/.cache/bower:/home/.cache/bower
      - ~/.local/bower:/home/.local/bower
      # NPM config
      - ~/.npm/:/home/.npm/
      # Workspace
      - ./:/workspace/
    command: sh -c "npm install --no-optional && gulp"

  app:
    image: allihoppa/allihoppa.nl:dev
    container_name: allihoppa-nl-app-dev
    build:
      context: ./docker/service/app/dev
    user: $HOST_UID:$HOST_GID
    volumes:
      - ./:/var/www
      - ~/.composer/:/home/.composer
    env_file:
      - environment/dev/db.env
      - environment/dev/wordpress.env
    environment:
      HOME: /home
      PHP_IDE_CONFIG: "serverName=allihoppa.nl.localhost"
      XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
    networks:
      default:
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=allihoppa"
      - "traefik.frontend.rule=Host:allihoppa.nl.localhost"
      - "traefik.port=8000"
      - "traefik.docker.network=traefik_webgateway"

  mysql:
    container_name: allihoppa-nl-db-dev
    user: $HOST_UID:$HOST_GID
    volumes:
      - ./environment/dev/db/init:/docker-entrypoint-initdb.d
      - ./environment/dev/db/data:/var/lib/mysql
    env_file:
      - environment/dev/db.env
