version: "2"

services:
  php-build:
    image: allihoppa/allihoppa.nl:php-build
    container_name: allihoppa-nl-php-build
    build:
      context: ./docker/build
    volumes:
      - ./:/var/www
      - ~/.composer/:/home/.composer
    user: $HOST_UID:$HOST_GID
    environment:
      HOME: /home
      SYMFONY_ENV: "dev"
      # Add the GITHUB_TOKEN which is needed to setup Composer authentication configuration.
      # This value is taken from a variable, or as the docs say:
      # "Environment variables with only a key are resolved to their values on the machine Compose is running on,
      # which can be helpful for secret or host-specific values."
      # See: # https://docs.docker.com/compose/compose-file/#/environment
      GITHUB_TOKEN: $GITHUB_TOKEN

  js-build:
    container_name: allihoppa-nl-js-build
    image: allihoppa/allihoppa.nl:js-build
    build:
      context: ./docker/js-build
    user: $HOST_UID:$HOST_GID
    environment:
      HOME: /home
    volumes:
      # Bower config
      - ~/.config/configstore/bower:/home/.config/configstore/bower
      - ~/.cache/bower:/home/.cache/bower
      - ~/.local/bower:/home/.local/bower
      # NPM config
      - ~/.npm/:/home/.npm/
      # Workspace
      - ./:/workspace/
    command: sh -c "npm install --no-optional && gulp"

  wordpress:
    image: allihoppa/allihoppa.nl:base
    build:
      context: ./docker/base
    tty: true
    ports:
      - 80:80
    volumes:
      - ./public:/var/www
    env_file:
      - environment/dev/db.env
      - environment/dev/wordpress.env

  mysql:
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    env_file:
      - environment/dev/db.env
