version: "2"

services:
  wordpress:
    image: allihoppa/allihoppa.nl
    container_name: allihoppa-nl-wordpress
    links:
      - mysql
    environment:
      DB_HOST: mysql

  mysql:
    container_name: allihoppa-nl-mysql
    image: mysql:5.5
    volumes:
      - ./mysql:/var/lib/mysql
