version: "2"

networks:
  traefik:
    external:
      name: traefik_webgateway

services:
  js-build:
    extends:
      file: ../default/docker-compose.yml
      service: js-build
    container_name: allihoppa-nl-js-build-dev
    command: sh -c "npm install --no-optional && gulp"

  app:
    extends:
      file: ../default/docker-compose.yml
      service: app-dev
    container_name: allihoppa-nl-app-dev
    env_file:
      - ./db.env
      - ./wordpress.env
    environment:
      PHP_IDE_CONFIG: "serverName=allihoppa.nl.localhost"
      XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_IP}"
    read_only: true
    tmpfs:
      - /var/lock:uid=${HOST_UID}
      - /var/run:uid=${HOST_UID}
      - /tmp:uid=${HOST_UID}
    hostname: allihoppa.nl.localhost
    networks:
      default:
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=allihoppa"
      - "traefik.frontend.rule=Host:allihoppa.nl.localhost"
      - "traefik.port=8000"
      - "traefik.docker.network=traefik_webgateway"

  mysql:
    extends:
      file: ../default/docker-compose.yml
      service: mysql
    container_name: allihoppa-nl-db-dev
    user: $HOST_UID:$HOST_GID
    environment:
      MYSQL_DATABASE_HOST: localhost
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - /tmp:/backup
    env_file:
      - ./db.env

  selenium-chrome:
    extends:
      file: ../ci/docker-compose.yml
      service: selenium-chrome
    # X windows cannot run as root
    user: $HOST_UID:$HOST_GID
    environment:
      DISPLAY: $DISPLAY
      HOME: /home
    # Chrome needs to have a home dir it can write to
    tmpfs:
      - /home:uid=$HOST_UID
    volumes:
      - ../../docker/service/selenium-chrome/entry_point-x11.sh:/opt/bin/entry_point.sh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
