version: "2"

networks:
  traefik:
    external:
      name: traefik_webgateway

services:
  js-build:
    container_name: allihoppa-nl-js-build-dev
    image: allihoppa/allihoppa.nl:js-build
    environment:
      HOME: /tmp
    user: $HOST_UID:$HOST_GID
    volumes:
      # Bower cache
      - ~/.cache/bower:/tmp/.cache/bower
      # NPM config
      - ~/.npm/:/tmp/.npm/
      # Workspace
      - ../../:/workspace/
    command: sh -c "npm install --no-optional && gulp"

  app:
    container_name: allihoppa-nl-app-dev
    image: allihoppa/allihoppa.nl:dev
    user: $HOST_UID:$HOST_GID
    volumes:
      - ../../:/var/www
      - ~/.composer/:/home/.composer
    env_file:
      - ./db.env
      - ./wordpress.env
    environment:
      HOME: /home
      PHP_IDE_CONFIG: "serverName=allihoppa.localhost"
      XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_NAME_OR_IP}"
      SERVER_NAME: "allihoppa.localhost"
    read_only: true
    tmpfs:
      - /var/lock:uid=${HOST_UID}
      - /var/run:uid=${HOST_UID}
      - /tmp:uid=${HOST_UID}
    hostname: allihoppa.localhost
    networks:
      default:
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=allihoppa"
      - "traefik.frontend.rule=Host:allihoppa.localhost"
      - "traefik.port=8000"
      - "traefik.docker.network=traefik_webgateway"

  mysql:
    container_name: allihoppa-nl-db-dev
    image: allihoppa/mysql:5.7
    user: $HOST_UID:$HOST_GID
    environment:
      MYSQL_DATABASE_HOST: localhost
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
      - /tmp:/backup
    env_file:
      - ./db.env

  behat:
    image: php:7.1-alpine
    volumes:
      - ../../:/var/www
    working_dir: /var/www

  selenium-chrome:
    container_name: allihoppa-nl-selenium-chrome-dev
    image: selenium/standalone-chrome:3.3
    volumes:

    # X windows cannot run as root
    user: $HOST_UID:$HOST_GID
    environment:
      DISPLAY: $DISPLAY
      HOME: /home
    # Chrome needs to have a home dir it can write to
    tmpfs:
      - /home:uid=$HOST_UID
    volumes:
      - ../../docker/service/selenium-chrome/entry_point-x11.sh:/opt/bin/entry_point.sh:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../tests/Resources/uploads:/tmp/uploads

  mail:
    image: schickling/mailcatcher
    container_name: allihoppa-nl-mail-dev
    networks:
      default:
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=allihoppa-mail"
      - "traefik.frontend.rule=Host:allihoppa-mail.nl.localhost"
      - "traefik.port=1080"
      - "traefik.docker.network=traefik_webgateway"
