version: '3'

volumes:
  apache-lock:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  apache-run:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  traefik:
    external:
      name: lucasvanlierop-website_default

services:
  app:
    image: allihoppa/allihoppa.nl:${DEPLOY_TAG}
    user: ${ALLIHOPPA_UID}:${ALLIHOPPA_GID}
    env_file:
      - ./db.env
      - ../default/wordpress.secret.env
      - ../default/wordpress.env
      - ./wordpress.env
    networks:
      default:
      traefik:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=allihoppa"
      - "traefik.frontend.rule=Host:www.allihoppa.nl,allihoppa.nl"
      - "traefik.port=8000"
      - "traefik.docker.network=lucasvanlierop-website_default"
    volumes:
      - apache-lock:/var/lock
      - apache-run:/var/run
      - /var/www/allihoppa/uploads:/var/www/public/wp-content/uploads

  mysql:
    image: allihoppa/mysql:5.5
    user: ${ALLIHOPPA_UID}:${ALLIHOPPA_GID}
    volumes:
      - /var/www/allihoppa/mysql/init/:/docker-entrypoint-initdb.d
      - /var/www/allihoppa/mysql/data/:/var/lib/mysql
    env_file:
      - ./db.env

  mysqldump:
    image: allihoppa/mysql:5.5
    user: ${ALLIHOPPA_UID}:${ALLIHOPPA_GID}
    volumes:
    - /var/www/allihoppa/mysql/backup/:/backup
    env_file:
     - ./db.env
    environment:
     MYSQL_DATABASE_HOST: mysql
    command: 'backup'
    deploy:
      restart_policy:
        condition: any
        delay: "1h"

  remote_backup:
    image: that1guy/docker-rclone
    user: ${ALLIHOPPA_UID}:${ALLIHOPPA_GID}
    env_file:
      - ./rclone.env
    volumes:
      - /var/www/allihoppa/uploads:/data/uploads
      - /var/www/allihoppa/mysql/backup:/data/mysql
    command: 'rclone -vv copy /data DROPBOX:/Allihoppa.nl/website_backup'
    deploy:
      restart_policy:
        condition: any
        delay: "1h"
